[package]
name = "app"
version = { workspace = true }
edition = { workspace = true }

[[bin]]
name = "Bristo"
path = "src/main.rs"

[dependencies]
common-debug = { path = "../common-debug" }
widget = { path = "../widget" }
status = { path = "../status" }
cleaner = { path = "../cleaner" }
log = { workspace = true }
anyhow = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
iced = { workspace = true }


[package.metadata.bundle.bin.Bristo]
name = "Bristo"
identifier = "com.ziprangga.Bristo"
icon = ["assets/Bristle.icns"]
version = "0.1.0"
copyright = "Copyright (c) 2026 ziprangga. Licensed under MIT or Apache-2.0."
category = "Utilities"
short_description = "Application Uninstaller"
